hl.on("hyprland.start", function()
	hl.exec_cmd("waybar")
	hl.exec_cmd("firefox")
	hl.exec_cmd("wpaperd")
	hl.exec_cmd("lxqt-policykit-agent")
	hl.exec_cmd("otd-daemon")
	hl.exec_cmd("nm-applet")
	hl.exec_cmd("modprobe v4l2loopback")
end)
